"""empty message

Revision ID: 9ba512625334
Revises: 0aae11bc5c06
Create Date: 2019-09-11 15:04:00.233647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba512625334'
down_revision = '0aae11bc5c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('task')
    op.add_column('report', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'ticket', ['ticket_id'], ['id'])
    op.drop_column('report', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('task_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'task', ['task_id'], ['id'])
    op.drop_column('report', 'ticket_id')
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('ticket')
    # ### end Alembic commands ###
