version: "3"
services:
  app:
    build: .
    image: app/children
    restart: always
    volumes:
      - ./app/:/app
    command: python3 /app/package.py
    ports:
      - "8008:8008"
#    depends_on:
#      - bot_postgres
#  bot_postgres:
#    build:
#      context: .
#      dockerfile: Dockerfile.postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
