version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: app/children
    restart: always
    volumes:
      - ./app/:/app
    command: python3 /app/package.py runserver -h 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    networks:
      - db_nw
    depends_on:
      - db
  db:
    image: postgres:10.10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - db_nw
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata: