version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/reporting-bot
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r app/dev-requirements.txt
      - run:
          name: Run tests
          command: pytest -svv app/tests --cov=app/reporting_app
